# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: android-build-variables
steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**'
    tasks: 'assembleDebug'

- task: AndroidSigning@2
  inputs:
    apkFiles: '**/*.apk'
    jarsign: true
    jarsignerKeystoreFile: 'production.keystore'
    jarsignerKeystorePassword: '$(keystore.password)'
    jarsignerKeystoreAlias: '$(key.alias)'
    jarsignerKeyPassword: '$(key.password)'
    zipalign: false

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1

- task: AppCenterDistribute@1
  inputs:
    serverEndpoint: 'Sharnitha_Appcenter'
    appSlug: 'https://appcenter.ms/orgs/Sharnithadevops/apps/Sharnitha-Android'
    appFile: '$(Build.SourcesDirectory)'
    
     